spring:
  application:
    name: yalta_project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yalta_project
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    ru.yalta: trace

bot:
  config:
    scheduler-init-delay: 1000
    message-receive-delay: 1000
    message-send-delay: 1000
  telegram:
    username: "yalta_city_bot"
    token: "1858534217:AAGk_4zGC92qgpzW_y3FTNT2W6f2rh4cBVA"


